config/routes.rb
Rails.application.routes.draw do

  get 'lista_usuarios/index'

   root 'zombies#index'

   devise_for :admins, controllers: {
     sessions: 'admins/sessions'
   }

   devise_for :users, controllers: {
     sessions: 'users/sessions'
   }
   resources :zombies do
  	resources :brains
   end

  get '/cerebros',to:'brains#index',as:'brains'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Mi aplicación en Ruby on Rails" %></title>

    <ul>
      <li>
        <li><%= image_tag 'icono.ico', class: 'icono'%></li>
      </li>
        <% if user_signed_in? || admin_signed_in? %>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropbtn">Zombies</a>
            <div class="dropdown-content">
              <%= link_to 'Lista de zombies', zombies_path %>
              <%= link_to 'Nuevo Zombie', new_zombie_path %>
            </div>
          </li>
            <li><%= link_to 'Cerrar sesión', destroy_user_session_path, :method => :delete %></li>
            <li><%= link_to 'Editar perfil', edit_user_registration_path %></li>
          <% if user_signed_in? %>
            <li><%= current_user.email %></li>
          <% else %>
            <li><%= current_admin.email %></li>
          <% end %>
        <% else %>
          <li><%= link_to 'Iniciar sesión', new_user_session_path %></li>
          <li><%= link_to 'Registro', new_user_registration_path %></li>
        <% end %>
</ul>

    <div class="container">
      <% flash.each do |key, value| %>
        <p class="alert alert-<%=key%>"><%= value %></p>
      <% end %>
</div>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>